### ISSUE TITLE
tesmart 16x1 hdmi kvm update

### ISSUE THREAD

**Issue by pictureinpicture** [bitfocus/companion-module-tesla-smart#3]
Hi there just put in a build request for the 16x1 kvm.  found that the 8 way module works fine but not the access toot he other 8 input.  is this something that can be easily updated?  API doc has been added just incase its needed.  And many thanks in advance.
[16x1 HDMI KVM CommunicationProtocol.pdf](https://github.com/bitfocus/companion-module-tesla-smart/files/6102836/16x1.HDMI.KVM.CommunicationProtocol.pdf)

**Comment by NoahCallaway** [comment]
It looks like this is available in the latest builds. 
You can find them on the bitfocus website under 'Beta Builds'.

**Comment by Julusian** [comment]
It looks like this should work
